### ISSUE TITLE
Discord link expired

### ISSUE THREAD

**Issue by jakewhelan** [dnl-fm/done#7]
Hey there!

Thanks for publishing Done, I'm evaluating it this week. I'm excited to have found something as promising as Done, and it be open source. If it's a match I would consider contributing too.

I wanted to join the discord community but the invite link in the README has expired, could you add a non-expiring invite link there instead?

@fightbulc

**Comment by fightbulc** [comment]
thanks @jakewhelan for reaching out. Happy to hear that Done might be helpful for you. Looking forward to hear your thoughts.

Greetings
Tino

**Comment by jakewhelan** [comment]
Sorry to be a nuisance

![image](https://github.com/dnl-fm/done/assets/6076073/6aa92ce8-ef1d-4fc4-a180-e36a5a8e4090)

🤔

**Comment by jakewhelan** [comment]
Oh, nope! There is another discord link at the bottom of the README, I was using that one.

![Uploading image.png…]()

**Comment by fightbulc** [comment]
Apologies, missed that one :) Will update now.
